version: '3.9'

services:
  nginx:
    container_name: nginx-lb
    image: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /Users/vnscriptkid/Desktop/Personal/SD-EBOOK/playground/load_balancer_nginx/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /Users/vnscriptkid/Desktop/Personal/SD-EBOOK/playground/load_balancer_nginx/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /Users/vnscriptkid/Desktop/Personal/SD-EBOOK/playground/load_balancer_nginx/nginx/index.html
        target: /Users/vnscriptkid/index.html
      - /Users/vnscriptkid/Desktop/Personal/SD-EBOOK/playground/load_balancer_nginx/nginx/web:/Users/vnscriptkid/web
      - /Users/vnscriptkid/Desktop/Personal/SD-EBOOK/playground/load_balancer_nginx/nginx/static:/Users/vnscriptkid/static
